### PR TITLE
added validation for text input

### LINKED ISSUE #3: Validation of text input fields before adding to the expense list
**Bug**
Empty text fields are being accepted and added to the existing expense list.

**Expected behaviour**
Text fields need to be validated before they are added to the Expense List. An alert box should pop up showing "Empty Fields not allowed!" if the fields are invalid.

**Screen Shots**
image
image

### PR DESCRIPTION
**Pull request by NachiketaVadera**
# Issue #3 

- Added text input validation in the form on an alert dialog.
- Updated dependencies.

### CODE REVIEW

**Review by ShreyaPillai — APPROVED** [review]
Great work!!

**Comment by ShreyaPillai** [comment]
Can you please send a screenshot where we can see the changes you made. I need to check it before merging this code into the main branch.
Thank you!

**Comment by NachiketaVadera** [comment]
@ShreyaPillai Sure. The following file was changed:
- `lib/widgets/addExpense.dart`

I've attached screenshots below. 
Screenshot_1601730077
Screenshot_1601730091

**Comment by tejasmorkar** [comment]
Thank you for your contribution! 👍 🎉

**Pull request merged**
